version: "3.8"

services:
  frontend:
    container_name: if-wizard-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 8765:5173
    restart: always
    tty: true
    volumes:
      - ./frontend:/app
      - if-wizard-frontend-node_modules:/app/node_modules
    command: npm run dev

  backend:
    container_name: if-wizard-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3980:3980
    volumes:
      - ./backend:/app
      - if-wizard-backend-node_modules:/app/node_modules
    tty: true
    depends_on:
      - database
    expose:
      - 3980
    env_file:
      - ./backend/.env

  database:
    image: postgres:15
    container_name: if-wizard-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "awesome_app_db"
      TZ: "Asia/Tokyo"
    ports:
      - 5678:5432

volumes:
  if-wizard-frontend-node_modules:
  if-wizard-backend-node_modules:
  postgres_data:
